export default function ResumeInput() {
  return (
    <div className='lg:ml-64 w-full mt-14 lg:mt-0 lg:w-[35vw] 2xl:w-[40vw] overflow-x-hidden overflow-y-scroll'>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
      <p>ResumeInput</p>
    </div>
  );
}
